### ISSUE TITLE
피드백

### ISSUE THREAD

**Issue by ggomma** [fierceCry/team_sparta_JavaScript_project#1]
# 구현 사항 확인

## 필수
- [x] jQuery 라이브러리 사용없이 순수 바닐라 자바스크립트 사용하기
- [x] TMDB 오픈 API를 이용하여 인기영화 데이터 가져오기
- [x] 영화정보 카드 리스트 UI 구현
  - [x] 카드 형태로 데이터 보여주기
  - [x] 제목, 내용 요약, 포스터, 평점 정보 포함
  - [x] 카드 클릭 시 영화 ID Alert 창 띄우기
- [x] 영화 검색 UI 구현
- [x] Javascript 문법 요소 이용
  - [x] const와 let만을 이용한 변수 선언 필수
  - [x] 화살표 함수 1개 이상 사용
  - [x] 배열 메소드 2개 이상 사용
  - [x] DOM 제어하기 메서드 2개 이상 사용

## 선택
- [x] CSS
  - [x] flex 사용하기
  - [ ] grid 사용하기
- [ ] 웹사이트 랜딩 또는 새로고침 후 검색 입력란에 커서 자동 위치시키기
- [x] 대소문자 관계없이 검색 가능하게 하기
- [x] 키보드 enter키를 입력해도 검색버튼 클릭한 것과 동일하게 검색 실행시키기

# 피드백

## 총평
- 코드를 잘 작성하였습니다.
- 코드의 기능을 잘 분리하여 잘 작성하였습니다.
- 현재 학습중인 내용에 대한 이해도가 매우 높은 것으로 보입니다.

### order
https://github.com/fierceCry/team_sparta_JavaScript_project/blob/0988eb9a18868257cb3ffe7f93e6e23d7cf79bcc/movie.js#L55

order를 나타내기 위해서는 일반적으로 'desc', 'asc'를 사용합니다. 일반적으로 사용하는 변수를 사용하는 경우 협업이 쉬워집니다.

### 가독성
https://github.com/fierceCry/team_sparta_JavaScript_project/blob/0988eb9a18868257cb3ffe7f93e6e23d7cf79bcc/movie.js#L14-L102

가독성을 위해 함수를 분리하는 것이 좋습니다. 현재는 `then()` 내부에 모든 함수가 들어가있지만 `createMovieCard`, `sortByRating`, `updateMovieList` 등을 밖으로 빼어내서 사용한다면 가독성이 조금 더 좋아집니다. 하나의 함수에서는 그 함수의 역할이 분명하게 드러나는 것이 좋습니다. 물론 해당 함수들을 바깥에서 사용할 일이 없기에 지금처럼 내부에 구현하는 것도 좋은 선택입니다.

### 주석
가장 잘 작성된 코드는 주석 없이 변수명이나 함수명을 읽기만 해도 이해할 수 있는 코드이고, 그 다음은 주석이 잘 작성되어 있는 코드입니다. 지금 작성하신 코드의 복잡도는 그리 높지 않아 굳이 주석을 작성할 필요는 없지만 평소에 주석을 잘 작성해두는 것이 프로젝트가 복잡해질 수록 도움이 됩니다.

## 추가 요소
아래 추가 개발을 권장하는 내용들입니다.
- 현재는 영화 정보를 1page 내에 있는 것들만 불러오고 있습니다. pagination을 이용한다면 더 많은 정보를 가져올 수 있습니다.
- 페이지가 로드된 후 검색창에 커서가 자동으로 위치할 수 있게 해보면 좋겠습니다.

**Comment by fierceCry** [comment]
1. 페이지 로드된 후 검색창에 커서 자동으로 위치이동 => focus()를 사용하여 완료
2. pagination를 사용하여 1page에서 불러오는것을 2페이지까지 분리완료
3. order를 'desc', 'asc' 수정 완료
